/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Power
 */
public class Category extends javax.swing.JFrame {

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        Players.pop=0;
        WheelB.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        WheelB = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Category");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("The host has to write the category of the secret phrase");

        WheelB.setText("Go to the wheel");
        WheelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WheelBActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WheelB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton))
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WheelB)
                    .addComponent(ExitButton))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String category = jTextField1.getText();
        if(Phrase.i==0){
            if(category.equalsIgnoreCase("")){
                jLabel2.setText("You've to write the caregory of this round");
            }else if(category.equalsIgnoreCase("Movie")){
                jLabel2.setText("The category is: " + category);
                jTextField1.setEnabled(false);
                WheelB.setEnabled(true);
            }else{
                jLabel2.setText("Wrong category of this round");
            }
        }else if(Phrase.i==1){
            if(category.equalsIgnoreCase("")){
                jLabel2.setText("You've to write the caregory of this round");
            }else if(category.equalsIgnoreCase("Food")){
                jLabel2.setText("The category is: " + category);
                jTextField1.setEnabled(false);
                WheelB.setEnabled(true);
            }else{
                jLabel2.setText("Wrong category of this round");
            }
        }else if(Phrase.i==2){
            if(category.equalsIgnoreCase("")){
                jLabel2.setText("You've to write the caregory of this round");
            }else if(category.equalsIgnoreCase("History")){
                jLabel2.setText("The category is: " + category);
                jTextField1.setEnabled(false);
                WheelB.setEnabled(true);
            }else{
                jLabel2.setText("Wrong category of this round");
            }
        }else if(Phrase.i==3){
            if(category.equalsIgnoreCase("")){
                jLabel2.setText("You've to write the caregory of this round");
            }else if(category.equalsIgnoreCase("Sports")){
                jLabel2.setText("The category is: " + category);
                jTextField1.setEnabled(false);
                WheelB.setEnabled(true);
            }else{
                jLabel2.setText("Wrong category of this round");
            }
        }else if(Phrase.i==4){
            if(category.equalsIgnoreCase("")){
                jLabel2.setText("You've to write the caregory of this round");
            }else if(category.equalsIgnoreCase("Geography")){
                jLabel2.setText("The category is: " + category);
                jTextField1.setEnabled(false);
                WheelB.setEnabled(true);
            }else{
                jLabel2.setText("Wrong category of this round");
            }
        }else if(Phrase.i==5){
            if(category.equalsIgnoreCase("")){
                jLabel2.setText("You've to write the caregory of this round");
            }else if(category.equalsIgnoreCase("Tournouaments")){
                jLabel2.setText("The category is: " + category);
                jTextField1.setEnabled(false);
                WheelB.setEnabled(true);
            }else{
                jLabel2.setText("Wrong category of this round");
            }
        }else if(Phrase.i==6){
            if(category.equalsIgnoreCase("")){
                jLabel2.setText("You've to write the caregory of this round");
            }else if(category.equalsIgnoreCase("Clubs")){
                jLabel2.setText("The category is: " + category);
                jTextField1.setEnabled(false);
                WheelB.setEnabled(true);
            }else{
                jLabel2.setText("Wrong category of this round");
            }
        }else if(Phrase.i==7){
            if(category.equalsIgnoreCase("")){
                jLabel2.setText("You've to write the caregory of this round");
            }else if(category.equalsIgnoreCase("Social Media")){
                jLabel2.setText("The category is: " + category);
                jTextField1.setEnabled(false);
                WheelB.setEnabled(true);
            }else{
                jLabel2.setText("Wrong category of this round");
            }
        }else if(Phrase.i==8){
            if(category.equalsIgnoreCase("")){
                jLabel2.setText("You've to write the caregory of this round");
            }else if(category.equalsIgnoreCase("Sience")){
                jLabel2.setText("The category is: " + category);
                jTextField1.setEnabled(false);
                WheelB.setEnabled(true);
            }else{
                jLabel2.setText("Wrong category of this round");
            }
        }else if(Phrase.i==9){
            if(category.equalsIgnoreCase("")){
                jLabel2.setText("You've to write the caregory of this round");
            }else if(category.equalsIgnoreCase("Economics")){
                jLabel2.setText("The category is: " + category);
                jTextField1.setEnabled(false);
                WheelB.setEnabled(true);
            }else{
                jLabel2.setText("Wrong category of this round");
            }
        }
        
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void WheelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WheelBActionPerformed
        // TODO add your handling code here:
        new Wheel().setVisible(true);
        dispose();
    }//GEN-LAST:event_WheelBActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Category().setVisible(true);
            }
        });
    }
    
    static int[] fsum = new int[3];
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton WheelB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
