/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Power
 */
public class Players extends javax.swing.JFrame {

    /**
     * Creates new form Players
     */
    public Players() {
        initComponents();
        getRootPane().setDefaultButton(GameB);
        jTextField2.setEnabled(false);
        Press2B.setEnabled(false);
        jTextField3.setEnabled(false);
        Press3B.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        GameB = new javax.swing.JButton();
        MenuB = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Press1B = new javax.swing.JButton();
        Press2B = new javax.swing.JButton();
        Press3B = new javax.swing.JButton();
        ExitB = new javax.swing.JButton();
        RefreshB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Players");

        jLabel1.setText("Write down the names of the players and press Enter to save the players!!!");

        jLabel2.setText("First player:");

        jLabel3.setText("Not saved!!!");

        jLabel4.setText("Second player:");

        jLabel5.setText("Not saved!!!");

        jLabel6.setText("Third player:");

        jLabel7.setText("Not saved!!!");

        GameB.setText("Start the game");
        GameB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameBActionPerformed(evt);
            }
        });

        MenuB.setText("Go back to the Menu");
        MenuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBActionPerformed(evt);
            }
        });

        jLabel8.setText("Status: ");

        jLabel9.setText("...");

        Press1B.setText("Press");
        Press1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Press1BActionPerformed(evt);
            }
        });

        Press2B.setText("Press");
        Press2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Press2BActionPerformed(evt);
            }
        });

        Press3B.setText("Press");
        Press3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Press3BActionPerformed(evt);
            }
        });

        ExitB.setText("Exit");
        ExitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBActionPerformed(evt);
            }
        });

        RefreshB.setText("Refresh");
        RefreshB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExitB))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GameB)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField2)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Press1B)
                                            .addComponent(Press2B))
                                        .addComponent(Press3B))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(MenuB)
                                    .addGap(10, 10, 10)))
                            .addComponent(RefreshB))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExitB)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(RefreshB)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(Press1B))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(Press2B))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(Press3B))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GameB)
                            .addComponent(MenuB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuBActionPerformed

    private void GameBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameBActionPerformed
        // TODO add your handling code here:
        if(pop==0)
            jLabel9.setText("You cannot play, because there are no participants. The game needs 3 players.");
        else if(pop==1)
            jLabel9.setText("You cannot play, because there is only one participant. The game needs 3 players.");
        else if(pop==2)
            jLabel9.setText("You cannot play, because there are only two participant. The game needs 3 players.");
        else if(pop==3){
            jLabel9.setText("You can play. Have fun!!!");
            new Category().setVisible(true);
        }
    }//GEN-LAST:event_GameBActionPerformed

    private void Press1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Press1BActionPerformed
        // TODO add your handling code here:
        s1 = jTextField1.getText();
        if(s1.equals("")){
            jLabel3.setText("Not saved!!!");
            jLabel9.setText("Press Refresh button to restore the names or type the name and then press the Press button");
        }else{
            jLabel3.setText("Saved!!!");
            pop++;
            jTextField1.setEnabled(false);
            Press1B.setEnabled(false);
            jTextField2.setEnabled(true);
            Press2B.setEnabled(true);
        }
        
    }//GEN-LAST:event_Press1BActionPerformed

    private void Press2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Press2BActionPerformed
        // TODO add your handling code here:
        s2 = jTextField2.getText();
        if(s2.equals("")){
            jLabel5.setText("Not saved!!!");
            jLabel9.setText("Press Refresh button to restore the names or type the name and then press the Press button");
        }else{
            jLabel5.setText("Saved!!!");
            pop++;
            jTextField2.setEnabled(false);
            Press2B.setEnabled(false);
            jTextField3.setEnabled(true);
            Press3B.setEnabled(true);
        }
    }//GEN-LAST:event_Press2BActionPerformed

    private void Press3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Press3BActionPerformed
        // TODO add your handling code here:
        s3 = jTextField3.getText();
        if(s3.equals("")){
            jLabel7.setText("Not saved!!!");
            jLabel9.setText("Press Refresh button to restore the names or type the name and then press the Press button");
        }else{
            jLabel7.setText("Saved!!!");
            pop++;
            jTextField3.setEnabled(false);
            Press3B.setEnabled(false);
        }
        
    }//GEN-LAST:event_Press3BActionPerformed

    private void ExitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBActionPerformed

    private void RefreshBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBActionPerformed
        // TODO add your handling code here:
        Press1B.setEnabled(true);
        jTextField1.setEnabled(true);
        jTextField1.setText("");
        Press2B.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField2.setText("");
        Press3B.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField3.setText("");
        jLabel3.setText("Not saved!!!");
        jLabel5.setText("Not saved!!!");
        jLabel7.setText("Not saved!!!");
        pop=0;
    }//GEN-LAST:event_RefreshBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Players.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Players.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Players.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Players.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Players().setVisible(true);
            }
        });
    }
    
    static String s1 = " ";
    static String s2 = " ";
    static String s3 = " ";
    
    static int pop=0;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitB;
    private javax.swing.JButton GameB;
    private javax.swing.JButton MenuB;
    private javax.swing.JButton Press1B;
    private javax.swing.JButton Press2B;
    private javax.swing.JButton Press3B;
    private javax.swing.JButton RefreshB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
