/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Power
 */
public class Wheel extends javax.swing.JFrame {

    /**
     * Creates new form Wheel
     */
    public Wheel() {
        initComponents();
        getRootPane().setDefaultButton(SpinB);
        NextB.setEnabled(false);
        jLabel1.setText(Players.s1 + ", spin the wheel!!!");
        jLabel5.setText("" + Category.fsum[0]);
        jLabel7.setText("" + Category.fsum[1]);
        jLabel9.setText("" + Category.fsum[2]);
        if(!Phrase.flag){
            if(Phrase.j==0){
                jLabel1.setText(Players.s1 + ", spin the wheel!!!");
            }else if(Phrase.j==1){
                jLabel1.setText(Players.s2 + ", spin the wheel!!!");
            }else if(Phrase.j==2){
                jLabel1.setText(Players.s3 + ", spin the wheel!!!");
            }
        }else if(Phrase.flag){
            if(Phrase.j==1){
                jLabel1.setText(Players.s1 + ", you lost your turn! " + Players.s2 + ", spin the wheel!!!");
            }else if(Phrase.j==2){
                jLabel1.setText(Players.s2 + ", you lost your turn! " +Players.s3 + ", spin the wheel!!!");
            }else{
                Phrase.j=0;
                jLabel1.setText(Players.s3 + ", you lost your turn! " +Players.s1 + ", spin the wheel!!!");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SpinB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NextB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wheel");

        SpinB.setText("Spin");
        SpinB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpinBActionPerformed(evt);
            }
        });

        NextB.setText("Next");
        NextB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBActionPerformed(evt);
            }
        });

        jLabel3.setText("Press the Next button to go search the secret phrase!");

        jLabel4.setText("First player score:");

        jLabel5.setText("jLabel5");

        jLabel6.setText("Second player score:");

        jLabel7.setText("jLabel7");

        jLabel8.setText("Third player score:");

        jLabel9.setText("jLabel9");

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SpinB, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(NextB)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ExitButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NextB)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(ExitButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SpinBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpinBActionPerformed
        // TODO add your handling code here:
        int wheelSpin[] = new int[1];
        wheelSpin[0] = (int)(1 + (25*Math.random()));
        if(wheelSpin[0]==1 || wheelSpin[0]==6 || wheelSpin[0]==11 || wheelSpin[0]==16 || wheelSpin[0]==21){
            result=50;
            jLabel2.setText("The price is: " + Integer.toString(result) + "EUROS");
            SpinB.setEnabled(false);
        }else if(wheelSpin[0]==2 || wheelSpin[0]==7 || wheelSpin[0]==12 || wheelSpin[0]==17 || wheelSpin[0]==22){
            result=100;
            jLabel2.setText("The price is: " + Integer.toString(result) + "EUROS");
            SpinB.setEnabled(false);
        }else if(wheelSpin[0]==3 || wheelSpin[0]==8 || wheelSpin[0]==13 || wheelSpin[0]==18 || wheelSpin[0]==23){
            result=150;
            jLabel2.setText("The price is: " + Integer.toString(result) + "EUROS");
            SpinB.setEnabled(false);
        }else if(wheelSpin[0]==4 || wheelSpin[0]==9 || wheelSpin[0]==14 || wheelSpin[0]==19 || wheelSpin[0]==24){
            result=200;
            jLabel2.setText("The price is: " + Integer.toString(result) + "EUROS");
            SpinB.setEnabled(false);
        }else if(wheelSpin[0]==5 || wheelSpin[0]==10 || wheelSpin[0]==15 || wheelSpin[0]==20 || wheelSpin[0]==25){
            result=250;
            jLabel2.setText("The price is: " + Integer.toString(result) + "EUROS");
            SpinB.setEnabled(false);
        }else
            jLabel2.setText("Error, spin again!!!");//very unlikely, but just in case
        NextB.setEnabled(true);
    }//GEN-LAST:event_SpinBActionPerformed

    private void NextBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBActionPerformed
        // TODO add your handling code here:
        new Phrase().setVisible(true);
        dispose();
    }//GEN-LAST:event_NextBActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wheel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wheel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wheel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wheel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wheel().setVisible(true);
            }
        });
    }
    
    
    static int result = 0;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton NextB;
    private javax.swing.JButton SpinB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
